[package]
name = "brstm"
version = "0.3.0"
edition = "2021"
description = "Crate to read and write brstm files"
license = "MIT"
repository = "https://github.com/lepelog/brstm-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
thiserror = "1.0.38"

[workspace]
members = ["music-randomizer"]
